spring:
  profiles:
    active:
      - dev
  thymeleaf:
    mode: LEGACYHTML5
server: 
  context-path: /fire-visual
  
  
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fire?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
  
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fire?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Root12345..
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080